version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8008:8008"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: waitress-serve --host=0.0.0.0 --port=8008 --call wsgi:create_app

  dashboard:
    build: .
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: streamlit run app/ui_streamlit.py --server.address=0.0.0.0 --server.port=8501
